import Head from "next/head";
import { useSession } from "next-auth/react";
import Link from "next/link";

export default function Home() {
  const { data: session, status } = useSession();
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav></nav>

      <main className="prose">
        {status === "authenticated" ? (
          <h2>Welcome {JSON.stringify(session.user)}</h2>
        ) : (
          <Link href="/api/auth/signin">Login</Link>
        )}
      </main>

      <footer></footer>
    </div>
  );
}
