import Head from "next/head";
import { useSession } from "next-auth/react";
import Link from "next/link";
import { GetServerSideProps } from "next";
import { getToken } from "next-auth/jwt";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav></nav>

      <main className="prose">
        <Link href="/api/auth/signin">Login</Link>
      </main>

      <footer></footer>
    </div>
  );
}

export const getServerSideProps: GetServerSideProps = async ({ req }) => {
  const token = await getToken({ req });
  if (!!token?.email) {
    return {
      redirect: {
        permanent: false,
        destination: `/dashboard`,
      },
    };
  }
  return {
    props: {},
  };
};
